name: simple_todo_app
description: "A simple Todo app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 3.0.2

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
